### ISSUE TITLE
Query: Data Storage for Generated Maps & Interest in Translating WordPress Plugin

### ISSUE THREAD

**Issue by wljrodrigues** [OpenGIS/Waymark#39]
Hello, I would like information about where on the server the data sent for the generated maps (geojson, kml...) are saved? I am interested in contributing to the translation of the WordPress plugin into Brazilian Portuguese. Thank you very much.

**Comment by morehawes** [comment]
Hi [wljrodrigues](https://github.com/wljrodrigues),

Thanks for reaching out :)

> I would like information about where on the server the data sent for the generated maps (geojson, kml...) are saved?

All data is stored in GeoJSON format, as a Custom Field (AKA Post meta data) with a key of `waymark_map_data`. You can view the data on the post edit screen by enabling [debug mode](https://www.waymark.dev/docs/settings/#misc-advanced) and ticking the "Custom Fields" option in the WordPress "Screen Options" interface (top right) on the post edit page.

I hope that helps and feel free ask if you have more questions.

> I am interested in contributing to the translation of the WordPress plugin into Brazilian Portuguese.

All help with translations is massively appreciated! ❤️ While I am not a translation editor and can not review translations myself, please do let me know if there is anything I can do to assist.

Cheers,

Joe

**Comment by wljrodrigues** [comment]
[morehawes](https://github.com/morehawes) Thank you for your attention.  Helped a lot! 🤝
