### ISSUE TITLE
Hide_marker override doesn't seem to work

### ISSUE THREAD

**Issue by YosoraLife** [OpenGIS/Waymark#41]
Hey, I love your work but i seem to running into some problems with the hide_marker override in the shortcode. 

If I understood your [documentation ](https://www.waymark.dev/docs/types/#type-keys) correctly, the shortcode should be hide_marker="photo":
![Screenshot 2024-05-16 223720](https://github.com/OpenGIS/Waymark/assets/61921490/aec95a4c-72ad-4317-8ea3-76cb7d70ab48)

But that doesn't seem to work. As a test I put the marker setting to hide on load (that works), but then show_marker doesn't work in that case either.

Am I doing something wrong?

**Comment by morehawes** [comment]
@YosoraLife,

Thank you for reaching out. I am also seeing this bug and will try to get it corrected in the near future.

Cheers,

Joe

**Comment by morehawes** [comment]
@YosoraLife,

I have just released version 1.1.8 of the plugin which should resolve this issue. Please do let me know if this is not the case for you.

Thanks again,

Joe

**Comment by YosoraLife** [comment]
Hi Joe,

Thanks for the quick response. I tested it on both a single map as a map collection and the issue is solved now.

Thank you,
Remco
