### ISSUE TITLE
Adding excerpt support

### ISSUE THREAD

**Issue by YosoraLife** [OpenGIS/Waymark#44]
[As discussed before:](https://github.com/OpenGIS/Waymark/pull/42#issuecomment-2123295848)

Would it also be an idea to add 'excerpt' to the supports array? Because now in a search query I get this as a result:

![Screenshot 2024-05-21 211800](https://github.com/OpenGIS/Waymark/assets/61921490/7c1bee15-2460-46d5-b109-6dcfa2a7467d)

While its text from the actual page it's not really in context. And it would be nice to have some text that actually makes some sense when you read it (and to have some control on what's displayed as excerpt). And unlike with the comment this doesn't affect anyone if there not using it, it just another possibility than can be used if you want to.

**Comment by morehawes** [comment]
Hi @YosoraLife,

I have released version 1.2.0 of the plugin which includes the ability to enable excerpt support.

Please do let me know if you encounter any issues!

Joe

**Comment by YosoraLife** [comment]
Hi Joe,

Nice solution ;) I tested it and for me it all works great. Thank you for your help.

Remco

**Comment by morehawes** [comment]
Great! Thanks for letting me know and again for the suggestion. 

Joe
