### ISSUE TITLE
Collection edit page refers to collections as categories

### ISSUE THREAD

**Issue by bviktor** [OpenGIS/Waymark#47]
So after finished editing / creating, it says:

> Item updated.
> ← Go to Categories

It may be an oversight, or just using some common language from other code, not sure.

**Comment by morehawes** [comment]
Thanks, will be updated in next release.

**Comment by bviktor** [comment]
Can confirm, indeed fixed in update, thank you:)

**Comment by morehawes** [comment]
Thanks for confirming.
